### ISSUE TITLE
[🙇🏼]下拉选择器默认暗黑模式颜色不对

### ISSUE THREAD

**Issue by xiaou66** [imzbf/vite-plugin-antd-theme#3]
![](https://cdn.jsdelivr.net/gh/xiaou66/picture@master/image/16319755541281c68b8555bc04dccb4a61cb01c56a1e7_tplv-k3u1fbpfcp-zoom-1.webp)
该图是 「vue3-admin」当然我本地也是有问题希望大佬修复一下求求🙇🏼

**Comment by imzbf** [comment]
ant用了一种不常用的less语法，这边研究下

**Comment by xiaou66** [comment]
暂时解决，我现在每次生成用注释的替换下面那两行😅
![image](https://user-images.githubusercontent.com/36022022/134346153-3c5b5dd2-e4a1-4dc7-851c-e83acae1553a.png)

**Comment by xiaou66** [comment]
跟插件这个插件没有关系,已经解决和动态样式导入有关系可以使用「vite-plugin-style-import」直接避免
